### PR TITLE
what is the grammar of graphics implemented in ggplot2

### PR DESCRIPTION
**Pull request by nacmarino**
I am creating this pull request to add information on one of the topics to be taugh in the lesson. This pull request is part of my instructor training checkout.

### CODE REVIEW

**Review by brymz — CHANGES_REQUESTED** [review]
Thanks for the contribution, @nacmarino! The content looks great and fits well as an intro to `ggplot2`.

I made a few in-line notes to address some language issues. Also, could you revise the first paragraph to have some structure? My idea is that each major question should be separated as a paragraph or bullet point.

**Comment by nacmarino** [comment]
Thank you for the feedback @brymz! I only now realized the typos, sorry.

I just pushed an improved version of the content. Is it better?

**Review by brymz — COMMENTED** [review]
Good work. This is much better.

Is the "Grammar of Graphics" a specific reference that might have a link? or are you just using it as a general Hadleyverse term?

**Comment by aflaxman** [comment]
@brymz : I have seen "Grammer of Graphics" attributed to Lee Wilkinson, who wrote a theory-of-viz book with that title: http://www.springer.com/us/book/9780387245447  If I have understood correctly, Hadley Wickham implemented Wilkinson's approach in `ggplot`.

**Comment by nacmarino** [comment]
Yes, this is correct! I believe that it would be more suitable to cite the work by Wilkinson here. How should we do it?

**Comment by brymz** [comment]
I think a link to the book or a related secondary (but accessible) site would do.

**Comment by nacmarino** [comment]
Here we go then! Link added.

**Comment by brymz** [comment]
Perfect.

**Review by brymz — APPROVED** [review]

**Pull request merged**
